# Generated by Django 6.1.1 on 2026-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                ("stock_actual", models.IntegerField(default=0)),
            ],
        ),
    ]
